# Generated by Django 4.1.5 on 2023-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_id',
            field=models.EmailField(default='email.com', max_length=50),
            preserve_default=False,
        ),
    ]
